# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Add the custom SQL script to the Docker image

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Expose the MySQL port
EXPOSE 3306


